<?php ob_start() ?>
<?php session_start() ?>
<?php
//function to store password as a hashed value
	   function randomString()
	   {
		   $string = md5(rand());
		   return $string;
	   }


$email = $_POST['member_email'];

//validate email fo valid maine account
if(preg_match("/[a-zA-z\.]+@(umit\.maine|maine)\.edu/", $email))
  {


	echo "<html><head><title>Chinese Zodiac Form (process_member_login.php)</title>";


	//Uses stylesheet to keep all pages consistent
	echo "<link rel='stylesheet' type='text/css' href='cz.css' /></head><body>";

	//Connects to the database
	require("inc_connect.php");

	//SQL query to see if users name,email,and password are already stored in the database; stores results into variable called $result

	$sql = mysql_query("SELECT * FROM cz_members4 where firstName='" . ($_POST['member_fname']) . "' and lastName='" . ($_POST['member_lname']) . "' and userName='" . $_POST['member_email'] . "'" ) or die(mysql_error());
	$result = mysql_fetch_array($sql);

			if ($result)
			  {
				//If the name, email, and password are found in the database
				// Check to see if the submitted password hash with the salt we have on file
				// matches the hash stored in the database

				if ($result['passwordHash'] == md5($_POST['member_password']. $result['passwordSalt']))
					{
					$_SESSION['id'] = $result['id'];
					$internId = $_SESSION['id'];



			   $message = "<h2 class = \"center\">Welcome to the Chinese Zodiac Social Networking Site</h2>";

			  /*----------------ADD BANNER HERE-----------------------*/


			   $message .= "   <p style = \"text-align:center\"><a href=\"view_member_list.php\">View the member list</a> | ";
  	           $message .= "   <a href=\"view_member_webpage.php?id=".
  	                 $_SESSION['id']."\">View my member web page</a> | ";
  	           $message .= "   <a href=\"member_update.php\">Update my information</a> | ";
  	           $message .= "   <a href=\"change_password.php?id=".
  	                 $_SESSION['id']."\">Change my password</a> | ";
  	           $message .= "   <a href =\"log_out.php\">Log out</a>\n";
  	           $message .= "<br /><br />";

	  echo $message;




					 } else
					 	{
					 		echo "Password does not match password on file.  Please go <a href='javascript:history.go(-1);'>back </a> and re-enter";
					 	}

				  }


			//If the name, email, and password are not found in the cz_members4 table,
			else if (!$result)
			 {

	           $hash = "";
 			   $new_password = randomString();
			   $salt = randomString();
			   $hash = md5($new_password . $salt);


			   	 $member_fname = $_POST['member_fname'];
			     $member_lname = $_POST['member_lname'];
			     $member_email = $_POST['member_email'];

			     //inserts values from form and the autogenerated password into the database

			     $sql = "INSERT INTO cz_members4 (firstName, lastName, chineseName, sign, element, compatible, YinYang, personality, image, UserName, passwordHash, passwordSalt) VALUES ('$member_fname', '$member_lname','', '', '', '', '', '', '','$member_email','$hash','$salt')";
			     $result = mysql_query($sql) or die(mysql_error());

				//set up the e-mail to the student with password

				$to = $_POST['member_email'];
				$subject = "Chinese Zodiac Social Networking Form Password";
				$body = "<html><head><link rel='stylesheet' type='text/css' href='http://cis.uma.edu/internship/styles.css' /></head>";
				$body .= "<body>Please type the following password as your Chinese Zodiac Password on your Log In form:<br />" . $new_password . "<br /></body></html>";

				$headers = 'MIME-Version:1.0' . "\n";
				$headers .= 'Content-type:text/html; charset=iso-8859-1' . "\n";
				$headers .= 'From: Social Networking Director <dkokoska@maine.edu>' . "\n";

				//defines arguments for the function
				mail($to,$subject,$body, $headers);

			   echo "<p> You should be receiving an auto-generated password shortly.  If you have any questions, please e-mail <a href = 'mailto:dkokoska@maine.edu'>Diana Kokoska, Social Networking Director</a>.</p>";

			 }
}
else if(!preg_match("/[a-zA-z\.]+@(umit\.maine|maine)\.edu/", $email))
{
echo "You did not enter a valid e-mail.  You must have a UMaine email address to use this site.";

}

?>
